### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [Gregwar/mongoose-cpp#25]
Hello,

I would like to know if the project is dead or not. I would like to use it but I think it might be too risky to use it for production if nobody maintains it

Thank you

**Comment by sambengtson** [comment]
For whatever it's worth, I use it in production.  For the most part, the library is simple enough to modify if you find yourself running into problems.  I'm familiar enough with it that I can help as well.

**Comment by Gregwar** [comment]
Hello,
I am not maintaining this actively
Note that this is not upstream with mongoose project (but you can feel free to open a PR if you do update it)

**Comment by GuillaumeLeclerc** [comment]
Thank you for your answers. We decided to use web sockets instead of raw HTTP requests so we won't need it. Moreover the license of the underlying Mongoose project is too strict for us.
