### ISSUE TITLE
Connecting using http to ssl port causes mongoose to infinite and CPU usage high

### ISSUE THREAD

**Issue by sswork** [Gregwar/mongoose-cpp#30]
If mongoose is configure to serve both http and https, then connecting to the https port using http in the browser causes mongoose hang or cpu usage high.

For example, if mongoose is set up to serve http on port 8081 and https on 8082:
http://localhost:8081 ==> works fine
https://localhost:8082 ==> works fine
http://localhost:8082 ==> request goes infinite

MONGOOSE_VERSION "5.2"
Please help me to resolve this issue.

**Comment by Gregwar** [comment]
Why closing? Did you fix it?

**Comment by sswork** [comment]
@Gregwar 

Thank you for you reply.
I found the solution for this from the following commit.
https://github.com/cesanta/mongoose/commit/27c665639811574e9d0e737938e1688fd171c1cf

But want to ask one think, does the latest mongoose supports WebDAV server. I mean, can we use mongoose as a WebDAV server?

Related issue:
https://github.com/cesanta/mongoose/issues/656
